version: "3"
services:
 guessmyword:
    container_name: guess-my-word-api
    #image: erezkon/adb-api:1
    build: .
    restart: always
    volumes:
      - ./Logs:/app/Logs
    ports:
      - "5123:5123"
      - "7123:7123"
